# Generated by Django 5.2.6 on 2025-11-10 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ConferenceApp", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="description",
            field=models.TextField(
                validators=[
                    django.core.validators.MaxLengthValidator(
                        30, "vous avez utuliser la limite des mots autorisés"
                    )
                ]
            ),
        ),
    ]
